MGMT-10919 - Use Pendo to track stats for vSphere
RedHatInsights/pendo-config-automation pull request #174
Opened 2022-07-14 08:46 UTC by jgyselov

https://issues.redhat.com/browse/MGMT-10919

We would like to start tracking vSphere-related controls in Assisted Installer, starting with the "Integrate with vSphere" switch and info-popover.

2022-07-17 10:58 UTC, jkilzi commented
Needs https://github.com/openshift-assisted/assisted-ui-lib/pull/1505

2022-07-17 10:59 UTC, jkilzi commented
LGTM

2022-07-18 13:23 UTC, ryelo requested changes
Trailing spaces are failing lint

2022-07-18 13:27 UTC, jkilzi commented on data/openshift.yml
> +      selectors:
```suggestion
      selectors:
```

2022-07-18 13:28 UTC, jkilzi reviewed
@jgyselov PTAL, there is a trailing white space

2022-07-18 13:28 UTC, jkilzi commented on data/openshift.yml
> +      selectors:
```suggestion
      selectors:
```

2022-07-21 20:28 UTC, jkilzi requested changes

2022-07-21 20:28 UTC, jkilzi commented on data/openshift.yml
> +      selectors:
@jgyselov this hasn't been solved yet the white space after the `:` is still there, line 422

2022-07-24 12:21 UTC, jkilzi approved these changes

2022-07-24 12:22 UTC, jkilzi commented
@ryelo FYI, trailing space removed

2022-08-31 12:07 UTC, ryelo approved these changes

2022-08-31 12:08 UTC, merged