Tracking for Agent-based installer interactions and others
RedHatInsights/pendo-config-automation pull request #187
Opened 2023-02-10 09:07 UTC by jgyselov

https://issues.redhat.com/browse/MGMT-11768
https://issues.redhat.com/browse/MGMT-13606

Related to: https://gitlab.cee.redhat.com/service/uhc-portal/-/merge_requests/3908

2023-02-23 08:36 UTC, jkilzi commented on data/openshift.yml
> +        - '{} [data-ouia-component-id="vsphere"] a:contains("Download installer")'
10x @celdrake. It was handled in 34a857eb22d76dac1536c74acb9c300c3686850b

2023-02-27 11:51 UTC, jgyselov commented on data/openshift.yml
> +        - '{} [data-ouia-component-id="vsphere"] a:contains("Download installer")'
We synced on the issue, it's on my to-do list.

2023-03-15 12:32 UTC, ryelo requested changes
Few linting errors

2023-03-15 12:32 UTC, ryelo commented on data/openshift.yml
> +    "Clusters - vSphere: Local Agent-based"
```suggestion
    "Clusters - vSphere: Local Agent-based":
```

2023-03-15 12:32 UTC, ryelo commented on data/openshift.yml
> +    "Clusters - Platform Agnostic: Local Agent-based"
```suggestion
    "Clusters - Platform Agnostic: Local Agent-based":
```

2023-03-15 12:34 UTC, jgyselov commented on data/openshift.yml
> +    "Clusters - Platform Agnostic: Local Agent-based"
Fixed, thank you!

2023-03-15 13:02 UTC, merged