Update url rules for cost managment.
RedHatInsights/pendo-config-automation pull request #25
Opened 2020-11-30 15:18 UTC by adberglund

## Summary
Navigation for cost management was recently changed and this should help track the change in Pendo.

2020-11-30 20:18 UTC, allieh782 approved these changes

2020-12-01 02:33 UTC, iphands requested changes

2020-12-01 02:34 UTC, iphands commented
@adberglund hey man have a look at the notes I left... Im not really sure if they apply to your case or not?
Happy to merge without, but I wanna check with you before I mash the button.

Cheers.

@allieh782 have a look also please

2020-12-01 14:56 UTC, adberglund commented
@iphands All great points. Added in the additional url_rules.

2020-12-01 22:18 UTC, iphands approved these changes

2020-12-01 22:18 UTC, iphands commented
@adberglund No prob... merging!

2020-12-01 22:18 UTC, merged